import type { ReactNode } from "react";

import Footer from "@/components/footer/Footer";
import Nav from "@/components/nav/Nav";

import type { Metadata } from "next";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  viewport: "width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html>
      <body>
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
